# Generated by Django 2.0.6 on 2018-06-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='사진을 넣어주세요', upload_to='profile_image'),
        ),
    ]
